prevent_proxy_connections: false
listeners:
- query_port: 25577
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - server-1
  bind_local_address: true
  host: 0.0.0.0:25577
  max_players: 40
  tab_size: 60
  force_default_server: false
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
log_pings: true
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 30000
player_limit: -1
ip_forward: true
groups:
  stouma915:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: e913de61-dba8-4f3b-bd97-3a5e25b69e60
online_mode: true
forge_support: false
disabled_commands:
- disabledcommandhere
servers:
  server-1:
    motd: '&1Just another BungeeCord - Forced Host'
    address: server-1:25565
    restricted: false
  server-2:
    motd: '&1Just another BungeeCord - Forced Host'
    address: server-2:25565
    restricted: false
